{{range $i, $value := .Values.microservices | default dict}}
{{if $value.enabled}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vechr-microservice-{{$value.name}}
  labels:
    app: vechr-microservice-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vechr-microservice-application
  template:
    metadata:
      name: vechr-microservice-service
      labels:
        app: vechr-microservice-application
    spec:
      restartPolicy: Always
      containers:
        - name: vechr-microservice-{{$value.name}}
          image: {{$value.image}}:{{$value.tag}}
          {{if and $value.externalPort}}
          ports:
            - name: http
              containerPort: {{$value.externalPort}}
              protocol: TCP
          {{ end }}
          imagePullPolicy: {{$value.imagePullPolicy | default "Always"}}
          {{ if $value.env}}
          env:
            {{range $i, $env_value := $value.env}}
            - name: {{$env_value.name}}
              value: {{quote $env_value.value}}
            {{end}}
          {{end}}
          # Resource Allocation
          {{- if $value.resources }}
          resources:
            requests:
              memory: {{ $value.resources.requests.memory | default "100Mi" | quote }}
              cpu: {{ $value.resources.requests.cpu | default "100m" | quote }}
            limits:
              memory: {{ $value.resources.limits.memory | default "1024Mi" | quote }}
              cpu: {{ $value.resources.limits.cpu | default "1" | quote }}
          {{- end}}

{{end}}
{{end}}