{{$namespace := include "vechr.namespace" .}}
{{$secretNameTLS := .Values.natsSelfSigned.secretName}}
{{range $i, $value := .Values.microservices | default dict}}
{{if $value.enabled}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vechr-microservice-{{$value.name}}
  namespace: {{ $namespace }}
  labels:
    svc: vechr-app-service
    app: vechr-service-{{$value.name}}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: vechr-app-service
      app: vechr-service-{{$value.name}}-app
  template:
    metadata:
      name: vechr-microservice-service
      labels:
        svc: vechr-app-service
        app: vechr-service-{{$value.name}}-app
    spec:
      restartPolicy: Always
      containers:
        - name: vechr-microservice-{{$value.name}}
          image: {{$value.image}}:{{$value.tag}}
          {{if and $value.externalPort}}
          ports:
            - name: http
              containerPort: {{$value.externalPort}}
              protocol: TCP
          {{ end }}
          imagePullPolicy: {{$value.imagePullPolicy | default "Always"}}
          {{ if $value.env}}
          env:
            - name: NATS_CA
              value: "/certificate/ca.crt"
            - name: NATS_KEY
              value: "/certificate/tls.key"
            - name: NATS_CERT
              value: "/certificate/tls.crt"
            - name: NATS_URL
              value: "nats://nats-lb.{{$namespace}}.svc.cluster.local:4222"
            - name: APP_PORT
              value: {{$value.externalPort | quote }}
            {{range $i, $env_value := $value.env}}
            - name: {{$env_value.name}}
              value: {{quote $env_value.value}}
            {{end}}
          {{end}}
          # Resource Allocation
          {{- if $value.resources }}
          resources:
            requests:
              memory: {{ $value.resources.requests.memory | default "100Mi" | quote }}
              cpu: {{ $value.resources.requests.cpu | default "100m" | quote }}
            limits:
              memory: {{ $value.resources.limits.memory | default "1024Mi" | quote }}
              cpu: {{ $value.resources.limits.cpu | default "1" | quote }}
          {{- end}}
          volumeMounts:
            - name: secret-nats
              mountPath: "/certificate/ca.crt"
              subPath: ca.crt
            - name: secret-nats
              mountPath: "/certificate/tls.crt"
              subPath: tls.crt
            - name: secret-nats
              mountPath: "/certificate/tls.key"
              subPath: tls.key

      volumes:
        - name: secret-nats
          secret:
            secretName: {{ $secretNameTLS }}
{{end}}
{{end}}