{{if .Values.gke.enabled}}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: vechr-backend-config
spec:
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"  
    affinityCookieTtlSec: 50
{{end}}