{{if .Values.gke.enabled}}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: vechr-backend-config
  namespace: {{ include "vechr.namespace" . }}
spec:
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"  
    affinityCookieTtlSec: 50
{{end}}