apiVersion: v1
kind: Service
metadata:
  name: vechr-microservice-service
  labels:
    app: vechr-microservice-application
  annotations:
    {{if $.Values.gke.enabled}}  
    # https://console.cloud.google.com/compute/healthChecks
    cloud.google.com/backend-config: 
      '{
        "ports": {
          "30036": "bc-audit-service",
          "30037": "bc-auth-service",
          "30038": "bc-db-logger-service",
          "30039": "bc-notification-service",
          "30040": "bc-things-service"
        }
      }'
    {{end}}
spec:
  type: NodePort
  selector:
    app: vechr-microservice-application
  ports:
    {{range $i, $value := .Values.microservices | default dict}}
    {{if and $value.externalPort $value.enabled}}
    - port: {{$value.externalPort}}
      targetPort: {{$value.externalPort}}
      nodePort: {{$value.nodePort}}
      protocol: TCP
      name: "http-{{$value.name}}"
    {{end}}
    {{end}}