{{if .Values.ingress.tls.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.ingress.tls.secretName}}
  namespace: {{ include "vechr.namespace" . }}
type: kubernetes.io/tls
data:
  ca.crt: {{.Values.ingress.tls.ca}}
  tls.crt: {{.Values.ingress.tls.cert}}
  tls.key: {{.Values.ingress.tls.key}}
{{end}}