{{if .Values.certmanager.ingressTLS.enabled}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certmanager.ingressTLS.name }}
  namespace: {{ include "vechr.namespace" . }}
type: kubernetes.io/tls
stringData:
  tls.key: ""
  tls.crt: ""
{{end}}