apiVersion: v1
kind: Service
metadata:
  name: vechr-microservice-service
  namespace: {{ include "vechr.namespace" . }}
  labels:
    svc: vechr-app-service
  annotations:
    {{if $.Values.gke.enabled}}
    cloud.google.com/backend-config: '{"default": "vechr-backend-config"}'
    {{end}}
spec:
  type: NodePort
  selector:
    svc: vechr-app-service
  ports:
    - port: 81
      name: "port-nothing"
      targetPort: 81
    {{range $i, $value := .Values.microservices | default dict}}
    {{if and $value.externalPort $value.enabled}}
    - port: {{$value.externalPort}}
      targetPort: {{$value.externalPort}}
      nodePort: {{$value.nodePort}}
      protocol: TCP
      name: "http-{{$value.name}}"
    {{end}}
    {{end}}