{
 "title": "All Performance Dashboards",
 "tags": [ "performance" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "app", "label": "Application", "query": { "query": "label_values(app)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(krakend_proxy_duration_bucket,http_route)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,5m,15m,30m,1h,2h,1d" },
   { "name": "max_list", "label": "Max items", "query": "3,5,10,15,20" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency  p99",
   "type": "stat",
   "description": "The percentile 99 tells you that 99% of  HTTP server requests have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\",http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency  p95",
   "type": "stat",
   "description": "The percentile 95 tells you that 95% of  HTTP server requests have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\",http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency  p90",
   "type": "stat",
   "description": "The percentile 90 tells you that 90% of  HTTP server requests have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\",http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency  p75",
   "type": "stat",
   "description": "The percentile 75 tells you that 75% of  HTTP server requests have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\",http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency  p50",
   "type": "stat",
   "description": "The percentile 50 tells you that 50% of  HTTP server requests have a latency below this number.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\",http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "description": "Numer of request per second received",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Worst latency",
   "type": "stat",
   "description": "The worst latency seen during the selected time",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\",http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "description": "Total incoming HTTP Requests in the selected period",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "stat",
   "description": "The Average Response Time in the selected period",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__range])) / (sum(rate(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__range]))+0.0001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg data throughput",
   "type": "stat",
   "description": "Average response size of data payloads per second in the selected period",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_response_size_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Avg Throughput",
   "type": "stat",
   "description": "Average requests per second over the selected period",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__range])-min_over_time(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__range]))/ $__range_s",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "timeseries",
   "description": "Average response latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))/count(max_over_time(http_server_duration_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencies (Percentile)",
   "type": "timeseries",
   "description": "The percentiles tell you the percentage of requests that responded within a time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (delta(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (delta(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (delta(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (delta(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (delta(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Response data size  (payloads)",
   "type": "timeseries",
   "description": "Bytes sent in body responses during the selected period. Headers excluded.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_response_size_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Avg reponse data size (payloads)",
   "type": "timeseries",
   "description": "Average response size of data payloads in the selected period",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_response_size_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]) / (1 +rate(http_server_response_size_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$__rate_interval])))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "description": "Number of request per second received",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "timeseries",
   "description": "Average response latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (http_request_method, http_route) (rate(http_server_duration_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))/sum by (http_request_method, http_route) (rate(http_server_duration_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "95p Endpoint Latencies",
   "type": "timeseries",
   "description": "The 95 percentile tells you that 95% of the requests responded within this time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_route, http_request_method) (rate(http_server_duration_bucket{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])))",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Avg response size per endpoint",
   "type": "timeseries",
   "description": "Bytes sent in body responses during the selected period. Headers excluded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(http_server_response_size_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Average response size per endpoint",
   "type": "bargauge",
   "description": "Average bytes sent in body responses for each endpoint during the selected period. Headers excluded.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_server_response_size_sum{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]) / rate(http_server_response_size_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval])",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Total response size per endpoint (top $max_list)",
   "type": "table",
   "description": "Bytes sent in body responses during the selected period. Headers excluded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($max_list, histogram_quantile(0.95, sum by (le, http_route) (rate(http_server_response_size_bucket{app=~\"$app\", instance=~\"$instance\"}[$__range])))) >= 0",
     "legendFormat": "{{http_route}}"
    }
   ]
  }
 ]
}