{
 "title": "Things Service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Apdex Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_duration_bucket{le=\"25\", status=~\"^2..$\", job=\"things-service\"}[1m])) / 2) + sum(rate(http_server_duration_bucket{le=\"50\", status=~\"^2..$\", job=\"things-service\"}[1m])) / sum(rate(http_server_duration_count{job=\"things-service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Apdex Score: target 25ms, tolerated: 100ms",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(http_server_duration_bucket{le=\"25\", status=~\"^2..$\", job=\"things-service\"}[1m])) + (sum(irate(http_server_duration_bucket{le=\"50\", status=~\"^2..$\", job=\"things-service\"}[1m])) / 2) / sum(irate(http_server_duration_count{job=\"things-service\"}[1m]))",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "Http Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Historic P90 response time by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, method, path) (rate(http_server_duration_bucket{job=\"things-service\"}[1m])))",
     "legendFormat": "{{method}}#{{path}}"
    }
   ]
  },
  {
   "title": "Historic P50 response time by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, method, path) (rate(http_server_duration_bucket{job=\"things-service\"}[1m])))",
     "legendFormat": "{{method}}#{{path}}"
    }
   ]
  },
  {
   "title": "HTTP Responses by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status, method) (increase(http_server_duration_count{job=\"things-service\"}[$__rate_interval]))",
     "legendFormat": "{{method}}: {{status}} status"
    }
   ]
  },
  {
   "title": "Top HTTP paths used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(path) (increase(http_server_duration_count{job=\"things-service\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Throughput by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(http_server_duration_count{job=\"things-service\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_duration_sum{job=\"things-service\"}[1m])) * 1) / sum(rate(http_server_duration_count{job=\"things-service\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Probe Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{status=~\"[40]..\", job=\"things-service\"}[1m])) by (job) / sum(rate(http_server_duration_count{job=\"things-service\"}[1m])) by (job)",
     "legendFormat": "error ratio"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(http_server_duration_count{job=\"things-service\"}[1m]))",
     "legendFormat": "total requests rate"
    },
    {
     "expr": "sum by(job) (rate(http_server_duration_count{status=\"500\", job=\"things-service\"}[1m]))",
     "legendFormat": "error responses rate"
    }
   ]
  }
 ]
}