{{if .Values.nats.enabled}}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigning
  namespace: {{ include "vechr.namespace" . }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-ca
  namespace: {{ include "vechr.namespace" . }}
spec:
  secretName: nats-ca
  duration: 8736h # 1 year
  renewBefore: 240h # 10 days
  issuerRef:
    name: selfsigning
    kind: ClusterIssuer
  commonName: nats-ca
  usages:
  - cert sign
  subject:
    organizations:
      - vechr.com
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nats-ca
  namespace: {{ include "vechr.namespace" . }}
spec:
  ca:
    secretName: nats-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.nats.config.cluster.tls.secretName }}
  namespace: {{ include "vechr.namespace" . }}
spec:
  secretName: {{ .Values.nats.config.cluster.tls.secretName }}
  duration: 2160h # 90 days
  renewBefore: 240h # 10 days
  issuerRef:
    name: nats-ca
    kind: Issuer
  usages:
  - signing
  - key encipherment
  - server auth
  - client auth
  subject:
    organizations:
      - vechr.com
  dnsNames:
    {{$replicaCount := .Values.nats.config.cluster.replicas | int}}
    {{range $i := until $replicaCount}}
    - "{{ $.Release.Name }}-nats-{{$i}}.{{ $.Release.Name }}-nats-headless"
    {{end}}
{{end}}