{{range $i, $value := .Values.serviceExternal.services | default dict}}
{{if $value.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$value.name}}
  labels:
    name: {{$value.name}}
spec:
  type: ExternalName
  externalName: {{$value.externalName}}
  ports:
  {{range $j, $port := $value.ports | default dict}}
  - port: {{$port.port}}
  {{end}}
{{end}}
{{end}}